In [60]:
import re
import pandas as pd

In [61]:
f=open("WhatsApp Chat with STUDY MATERIAL GROUP✍️.txt",'r',encoding = 'utf-8')

In [62]:
data = f.read()

In [63]:
print(data)

3/15/24, 10:40 AM - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. Learn more.
10/11/23, 1:27 PM - ~ Bhargav Patel created group "STUDY MATERIAL GROUP✍️"
3/15/24, 10:40 AM - Om ᴀ ʀ ʏ ᴀ ɴ added you
3/15/24, 10:40 AM - Om ᴀ ʀ ʏ ᴀ ɴ added Darbar
3/15/24, 12:22 PM - Om ᴀ ʀ ʏ ᴀ ɴ: <Media omitted>
3/15/24, 12:22 PM - Om ᴀ ʀ ʏ ᴀ ɴ: <Media omitted>
3/15/24, 12:22 PM - Om ᴀ ʀ ʏ ᴀ ɴ: <Media omitted>
3/15/24, 12:22 PM - Om ᴀ ʀ ʏ ᴀ ɴ: <Media omitted>
3/15/24, 12:22 PM - Om ᴀ ʀ ʏ ᴀ ɴ: <Media omitted>
3/15/24, 12:24 PM - Om.    Deep: <Media omitted>
3/15/24, 12:24 PM - Om.    Deep: <Media omitted>
3/15/24, 12:24 PM - Om.    Deep: <Media omitted>
3/15/24, 12:24 PM - Om.    Deep: <Media omitted>
3/15/24, 12:24 PM - Om.    Deep: <Media omitted>
3/16/24, 10:38 AM - Om. Jenil: This message was deleted
3/16/24, 10:38 AM - Om ᴀ ʀ ʏ ᴀ ɴ: This message was deleted
3/16/24, 10:38 AM - Om ᴀ ʀ ʏ ᴀ ɴ: This message was deleted
3/31/24, 11:58 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Arreeee result joy lau aavi gyuuu
3/31/24, 11:58 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Jaldi
3/31/24, 11:58 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Lodau
3/31/24, 12:03 PM - Bapu: Kya link to mokl wedsite ne
3/31/24, 12:03 PM - +91 94287 92992: Khoti chodino che
3/31/24, 12:03 PM - Bapu: Avaj loda 6 aya🤣🤣
3/31/24, 12:04 PM - +91 94287 92992: E j ne
3/31/24, 12:04 PM - Om.    Deep: 😂
3/31/24, 12:04 PM - devganiyaharsh: 😂😂😂
3/31/24, 12:04 PM - Om.    Deep: Kon che
3/31/24, 12:04 PM - +91 94287 92992: Rand
3/31/24, 12:04 PM - Bapu: Brand🤣🤣
3/31/24, 12:04 PM - Om Darshan: 🤣
3/31/24, 12:06 PM - Om ᴀ ʀ ʏ ᴀ ɴ: Pikina
3/31/24, 12:07 PM - Om ᴀ ʀ ʏ ᴀ ɴ: Loda
3/31/24, 12:07 PM - Om ᴀ ʀ ʏ ᴀ ɴ: Tention na lyo badha pass thay jaso lodau
3/31/24, 12:08 PM - Bapu: Jane loda tu ayathi etle ame pass j 6😂😂
3/31/24, 12:08 PM - Om ᴀ ʀ ʏ ᴀ ɴ: Pikina
3/31/24, 12:08 PM - Bapu: Apsbd ny
4/10/24, 10:01 AM - Om Darshan: <Media omitted>
4/10/24, 10:01 AM - Om Darshan: <Media omitted>
4/10/24, 10:01 AM - Om Darshan: <Media omitted>
4/10/24, 10:01 AM - Himanshu: <Media omitted>
4/10/24, 10:01 AM - Himanshu: <Media omitted>
4/10/24, 10:01 AM - Himanshu: <Media omitted>
4/10/24, 10:01 AM - Himanshu: <Media omitted>
4/10/24, 11:11 AM - +91 94287 92992: <Media omitted>
4/10/24, 11:16 AM - Om Darshan: <Media omitted>
4/10/24, 11:16 AM - Om Darshan: <Media omitted>
4/10/24, 11:16 AM - Om Darshan: <Media omitted>
4/10/24, 11:16 AM - Om Darshan: <Media omitted>
4/10/24, 11:16 AM - Om Darshan: <Media omitted>
4/10/24, 11:16 AM - Om Darshan: <Media omitted>
4/10/24, 11:16 AM - Om Darshan: <Media omitted>
4/12/24, 12:47 PM - Om Darshan: <Media omitted>
4/12/24, 12:48 PM - Om Darshan: <Media omitted>
4/12/24, 12:48 PM - Om Darshan: <Media omitted>
4/12/24, 12:48 PM - Om Darshan: <Media omitted>
4/12/24, 12:48 PM - Om Darshan: <Media omitted>
4/13/24, 11:26 AM - Om Mayur: <Media omitted>
4/25/24, 9:41 AM - +91 94287 92992: <Media omitted>
4/25/24, 9:41 AM - +91 94287 92992: <Media omitted>
4/25/24, 9:41 AM - +91 94287 92992: <Media omitted>
4/25/24, 9:41 AM - +91 94287 92992: <Media omitted>
4/25/24, 9:41 AM - +91 94287 92992: <Media omitted>
4/25/24, 9:41 AM - +91 94287 92992: <Media omitted>
4/25/24, 9:41 AM - +91 94287 92992: <Media omitted>
4/25/24, 9:41 AM - +91 94287 92992: <Media omitted>
4/28/24, 11:22 AM - Om Darshan: Kale aavana ne
4/28/24, 11:23 AM - Bapu: Ha ha
4/28/24, 11:23 AM - Bapu: Kal avjo badhat
4/28/24, 11:23 AM - Bapu: Badhay
5/2/24, 8:21 AM - Bapu: <Media omitted>
5/2/24, 8:21 AM - Bapu: Ela ato bhdvay kyri aniye
5/2/24, 8:21 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Ha yr
5/2/24, 8:22 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Have su kar vu
5/2/24, 8:22 AM - Bapu: Me phn kyroto aghdi ene
5/2/24, 8:22 AM - Bapu: K tmne puuchhi ne to raykhu
5/2/24, 8:22 AM - devganiyaharsh: Aene Kay hostel vala to ghare vaya gya
5/2/24, 8:22 AM - Bapu: To k kal puchhva ka no ayva
5/2/24, 8:22 AM - Bapu: Mne ke kal avi jav pachhi rakhi dejo
5/2/24, 8:22 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Aene ke tu kya hato kale
5/2/24, 8:23 AM - Bapu: Me ej kidhu eke phn kyro hot to
5/2/24, 8:23 AM - Bapu: Mne ke aya badhay mne key k cours baki 6 ne km rja api dyo tme
5/2/24, 8:23 AM - Om ᴀ ʀ ʏ ᴀ ɴ: To aene ke aaje Kari didho ne have 😁
5/2/24, 8:23 AM - Bapu: Ela land 6 eye
5/2/24, 8:23 AM - Bapu: Hve su krvu kal nu
5/2/24, 8:23 AM - Om ᴀ ʀ ʏ ᴀ ɴ: To yr
5/2/24, 8:25 AM - devganiyaharsh: Bhavala phone Kari ne ke ke hostel vala to ghare vaya gya 😂
5/2/24, 8:25 AM - devganiyaharsh: Chhe
5/2/24, 8:25 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Hn
5/2/24, 8:26 AM - Om ᴀ ʀ ʏ ᴀ ɴ: M Kaik Karo to thay have
5/2/24, 8:27 AM - Bapu: Ha Halo ne kyk kriye
5/2/24, 8:27 AM - Bapu: Ela ek var to kyro😂
5/2/24, 8:28 AM - Bapu: Ene loda ne bija upadta hoy ke aa badhay km aam rja rakhe
5/2/24, 8:28 AM - Bapu: Etle
5/2/24, 8:28 AM - Om.    Deep: Aaj kon kon gaya
5/2/24, 8:28 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Koy nai 😁
5/2/24, 8:29 AM - Bapu: Koy nath gyu ela
5/2/24, 8:29 AM - Om.    Deep: To su koy jata nay
5/2/24, 8:29 AM - devganiyaharsh: 😄😄
5/2/24, 8:30 AM - devganiyaharsh: Hooop
5/2/24, 8:30 AM - Bapu: 😂😂
5/2/24, 8:41 AM - +91 94287 92992: Kale javanu ke nay?
5/2/24, 8:41 AM - Om.    Deep: Nay
5/2/24, 8:41 AM - Bapu: Na na hve thodi jvay
5/2/24, 8:41 AM - +91 94287 92992: Ene phone ma su kidhu
5/2/24, 8:41 AM - Om.    Deep: Jene jiya khila khod va hoy e khodi le
5/2/24, 8:42 AM - Bapu: Eke kal puchhi lidhu hot to mne
5/2/24, 8:42 AM - +91 94287 92992: Ane kidhu ke aavi jajo
5/2/24, 8:42 AM - Om.    Deep: Aene kay AEK var to kidhu
5/2/24, 8:42 AM - Bapu: Eke kal avi jajo
5/2/24, 8:43 AM - Om.    Deep: Hostel vadanu kidhu to su kidhu
5/2/24, 8:43 AM - Bapu: Na e nthi kidhu
5/2/24, 8:43 AM - +91 94287 92992: Hostel varav kok phone kari ko ke ame su karye
5/2/24, 8:44 AM - Bapu: Ha ela deepla tu phn kar
5/2/24, 8:44 AM - Bapu: Ene ky ame ghre avta rya
5/2/24, 9:05 AM - Om. Jenil: Su krvanu aa to ke j bhavesh
5/2/24, 9:06 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Kevuj padche tane
5/2/24, 9:06 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Baki nai chale
5/2/24, 9:06 AM - Om. Jenil: Right 👍
5/2/24, 9:06 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Ohhh
5/2/24, 9:07 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Bhavesh ke se toj chal che ne
5/2/24, 9:07 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Amaro to nai gam to
5/2/24, 9:07 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Tane
5/2/24, 9:07 AM - Om. Jenil: Badhani pela tu Leto to
5/2/24, 9:07 AM - Om. Jenil: Aa dekhay j chhe 😂
5/2/24, 9:07 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Bhavesh bol jaldi baki jenil ne kaik thay jase bhai
5/2/24, 9:08 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Tyare bhavesh Mane ke Toto ke jenil Maro lodo mage se 😁
5/2/24, 9:08 AM - Om ᴀ ʀ ʏ ᴀ ɴ: To pachi me kidhu ke aapi de aene taro j fave
5/2/24, 9:09 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Bija koy na maja nathi aavti
5/2/24, 9:18 AM - devganiyaharsh: નથી બિતા જેને જ્યાં ખીલા ખોડવા હોય nya khodi de 😂
5/2/24, 9:19 AM - devganiyaharsh: Mahesh ne kyo Mahesh ne
E boss chhe
5/2/24, 9:21 AM - devganiyaharsh: 😂😂
5/2/24, 9:21 AM - devganiyaharsh: Hamna phone karse e
5/2/24, 9:21 AM - devganiyaharsh: E no bive ho 😂
5/2/24, 10:01 AM - Om. Jenil: Aano leva gyo to m ne 😂
5/2/24, 10:01 AM - Om. Jenil: Aatle tne bov kidhu 😂😂
5/2/24, 10:02 AM - Om. Jenil: Bhavesh mja aavi ne brand ma 😂😂
5/2/24, 10:05 AM - Om ᴀ ʀ ʏ ᴀ ɴ: Have aava message nai kar to Bhai
5/2/24, 10:05 AM - Om. Jenil: Chalu Kone krya
5/3/24, 4:46 PM - Om ᴀ ʀ ʏ ᴀ ɴ: Aaje gya ta koy ke nai ?
5/3/24, 4:51 PM - devganiyaharsh: Nay bhai
5/3/24, 5:14 PM - Om. Jenil: Koi nthi gyu
5/3/24, 5:23 PM - devganiyaharsh: Paku ne
5/3/24, 5:32 PM - Om ᴀ ʀ ʏ ᴀ ɴ: Okay
5/3/24, 5:35 PM - Om. Jenil: Ha
5/3/24, 5:35 PM - Om. Jenil: Bhai
5/3/24, 8:13 PM - devganiyaharsh: To vandho nay
5/3/24, 8:13 PM - devganiyaharsh: Tu hasti chho tane to khbr j hoy ne <This message was edited>
5/3/24, 8:15 PM - Bapu: 🤣🤣🤣
5/3/24, 9:09 PM - Om ᴀ ʀ ʏ ᴀ ɴ: Ae vatt 100 taka sachi ho
5/3/24, 9:09 PM - Om ᴀ ʀ ʏ ᴀ ɴ: Jenil Seth 🖕🖕
5/4/24, 1:44 PM - Om. Jenil: <Media omitted>
5/4/24, 2:01 PM - Om.    Deep: Vah Jenil bhai tari pase kiyathi
5/4/24, 2:21 PM - Om. Jenil: Nayan Joshi aa moklyu
5/4/24, 2:22 PM - Om.    Deep: Kema group ma
5/4/24, 4:39 PM - Om. Jenil: Nayan aa banvyu tu aa
5/7/24, 12:03 PM - Om Mayur: Koi pase lab manual na photo hoy to mokljo
5/7/24, 12:51 PM - Om. Jenil: <Media omitted>
5/7/24, 12:51 PM - Om. Jenil: <Media omitted>
5/7/24, 1:15 PM - devganiyaharsh: Hosiyar ho Jenil bhai
5/7/24, 1:28 PM - Om. Jenil: Na Bhai
5/7/24, 1:29 PM - Om. Jenil: Tmari jetla ny
5/7/24, 2:30 PM - Om Mayur: Jenil nava mokalne a lakhay Gaya chhe
5/7/24, 2:37 PM - Om. Jenil: Aavu chhe 😂
5/7/24, 5:30 PM - Om Mayur: Pps nu homework Thai gayu
5/7/24, 5:30 PM - Om Darshan: Kyu
5/7/24, 5:30 PM - Om Mayur: Defination
5/7/24, 5:30 PM - Om Mayur: Aecu kaik lakhavanu hatu
5/7/24, 5:30 PM - Om Darshan: Na
5/7/24, 5:31 PM - Om Mayur: Lab manual kya sudhi lakhavani chhe
5/7/24, 5:34 PM - Om Darshan: 38
5/7/24, 5:34 PM - Om Darshan: Kadach
5/7/24, 5:34 PM - Om Darshan: Ka 39
5/7/24, 5:34 PM - Om Mayur: Tare lakhay gaya
5/7/24, 5:35 PM - Himanshu: 29,30,31,32,33,37
5/7/24, 5:35 PM - Om Mayur: To maklje mane
5/7/24, 5:36 PM - +91 94287 92992: Halo ff
5/7/24, 5:37 PM - Om Darshan: Thodik var pachi
5/7/24, 7:37 PM - Om Darshan: Kal javu ne
5/7/24, 7:37 PM - Om Darshan: 😅🤣
5/7/24, 7:39 PM - Om.    Deep: Kiya
5/7/24, 8:05 PM - Bapu: Ye kab ho gya itna sara Bhai 🤣🤣
5/7/24, 8:05 PM - Bapu: Hu to kv somvare Jaye hve😜😂
5/7/24, 8:30 PM - Om Darshan: Na bhai
5/7/24, 8:32 PM - Bapu: 😂😂👍
5/9/24, 3:48 PM - +91 94287 92992: Recheck nu result aavi gyu
5/9/24, 4:22 PM - Bapu: Hkn
6/3/24, 2:02 PM - Om Mayur: Series solution
1) classified singularity (3 or 4 mark)
2) series solution at ordinary point (7 mark confirm)
3) series solution at regular sigular point (7- mark confirm)
4) bachi J 1/2 -1/2 3/2 -3/2 mathi ak example (4 mark)
5) recrence relation no ek examples (3- mark)
6/3/24, 2:02 PM - Om Mayur: First order firest degree
1) excet diff.
2) liner diff.
3) Bernoulli diff.
Aa 3 method mathi 2 method confirm hse j
6/3/24, 2:02 PM - Om Mayur: Baki
Solvable for p , x and y mathi hoi aa may b option ma nikdi jai
6/3/24, 2:02 PM - Om Mayur: Laplece mathi
Convolution theorem
Partial plfraction
2nd shifting
Nd bdhi property no mix examples
6/3/24, 2:07 PM - Om Darshan: This message was deleted
6/4/24, 9:15 AM - Om Darshan: <Media omitted>
7/16/24, 9:58 AM - Om Darshan: Hii
7/16/24, 9:58 AM - Om Darshan: Hello
7/16/24, 9:58 AM - Om Darshan: Internal marks joi lejo badha
7/16/24, 9:58 AM - +91 94287 92992: Hi
7/16/24, 9:58 AM - +91 94287 92992: Link send karjene
7/16/24, 10:00 AM - Om Darshan: Google mar
7/30/24, 12:10 PM - Himanshu: <Media omitted>
8/1/24, 12:20 PM - Om.   Jash: <Media omitted>
8/1/24, 12:20 PM - Om.   Jash: <Media omitted>
8/2/24, 12:38 PM - Om Darshan: <Media omitted>
8/8/24, 10:52 AM - Om.    Deep: 8P7 WQZ 2NG
8/12/24, 1:48 PM - Om Darshan: <Media omitted>
8/30/24, 12:59 PM - Om.   Jash: <Media omitted>
9/2/24, 5:05 PM - Om Mayur: This message was deleted
9/2/24, 5:07 PM - Om Mayur: <Media omitted>
9/2/24, 5:09 PM - Om Mayur: <Media omitted>
9/2/24, 5:09 PM - Om Mayur: <Media omitted>
9/2/24, 5:09 PM - Om Mayur: <Media omitted>
9/2/24, 5:10 PM - Om Mayur: <Media omitted>
9/2/24, 5:10 PM - Om Mayur: <Media omitted>
9/2/24, 5:10 PM - Om Mayur: <Media omitted>
9/2/24, 5:10 PM - Om Mayur: <Media omitted>
9/2/24, 5:10 PM - Om Mayur: <Media omitted>
9/2/24, 5:10 PM - Om Mayur: <Media omitted>
9/2/24, 5:10 PM - Om Mayur: <Media omitted>
9/2/24, 5:10 PM - Om Mayur: <Media omitted>
9/2/24, 5:10 PM - Om Mayur: <Media omitted>
9/2/24, 5:11 PM - Om Mayur: <Media omitted>
9/2/24, 5:11 PM - Om Mayur: <Media omitted>
9/12/24, 6:28 AM - Om Mayur: Test che
9/12/24, 6:28 AM - Om Mayur: DBMS
9/12/24, 6:28 AM - Om Mayur: Ha ke na
9/12/24, 6:43 AM - Om Darshan: Ha syd
9/12/24, 7:10 AM - Bapu: Nathi nathi
9/12/24, 7:10 AM - Om Mayur: Oo
9/12/24, 7:11 AM - Bapu: Nathi test ela moj kro
9/12/24, 7:11 AM - Om Mayur: Ok
9/12/24, 7:11 AM - Bapu: 😂😂
9/12/24, 9:54 AM - YASH YATIN: Na
9/13/24, 9:17 AM - Himanshu added Balva Maulik
9/13/24, 10:02 AM - Darbar: <Media omitted>
9/13/24, 10:02 AM - Darbar: <Media omitted>
9/13/24, 10:02 AM - Darbar: <Media omitted>
9/14/24, 1:51 PM - Om Darshan: <Media omitted>
9/30/24, 1:06 PM - Himanshu: <Media omitted>
10/8/24, 10:53 AM - Om Darshan: <Media omitted>
10/8/24, 10:53 AM - Om Darshan: <Media omitted>
10/8/24, 10:53 AM - Himanshu added Om. Khush
10/8/24, 11:48 AM - Himanshu: <Media omitted>
10/8/24, 11:48 AM - Himanshu: <Media omitted>
10/8/24, 11:48 AM - Himanshu: <Media omitted>
10/8/24, 11:48 AM - Himanshu: <Media omitted>
10/9/24, 12:47 PM - devganiyaharsh: <Media omitted>
10/10/24, 1:49 PM - Om. Khush: <Media omitted>
10/14/24, 1:00 PM - Om. Khush: <Media omitted>
10/14/24, 1:00 PM - Om. Khush: <Media omitted>
10/15/24, 11:22 AM - +91 94287 92992: <Media omitted>
10/15/24, 11:46 AM - Om. Khush: <Media omitted>
10/17/24, 1:37 PM - Darbar: <Media omitted>
10/17/24, 1:39 PM - Himanshu: A su che Bhai seni Tarik che
10/17/24, 1:39 PM - Bapu: Gtu. Ni chhe n
10/17/24, 1:40 PM - Darbar: 3 sem exam
10/17/24, 1:40 PM - Himanshu: Gtu
10/17/24, 1:40 PM - Himanshu: Ni
10/17/24, 1:42 PM - Om Mayur: Ha
10/17/24, 1:44 PM - +91 94287 92992: Sem 3 nu time table send karoto
10/17/24, 1:44 PM - +91 94287 92992: All branch varu
10/17/24, 2:02 PM - Om.   Jash: <Media omitted>
10/17/24, 2:02 PM - Om.   Jash: Branch code joi leje ama
10/18/24, 10:02 AM - Himanshu: <Media omitted>
10/18/24, 6:16 PM - Om.   Jash: <Media omitted>
10/18/24, 6:16 PM - Om.   Jash: <Media omitted>
10/18/24, 6:16 PM - Om.   Jash: <Media omitted>
10/18/24, 6:16 PM - Om.   Jash: <Media omitted>
10/18/24, 6:16 PM - Om.   Jash: <Media omitted>
10/18/24, 6:16 PM - Om.   Jash: <Media omitted>
10/19/24, 1:54 PM - Om Mayur: 7/11 to 19/11 submission all subjects
10/19/24, 2:23 PM - Om.   Jash: Revision classs?
10/19/24, 2:24 PM - Om Mayur: Kese pachi
10/20/24, 3:29 PM - YASH YATIN: <Media omitted>
10/21/24, 3:34 PM - Om.   Jash: <Media omitted>
10/22/24, 11:37 AM - Om.   Jash: <Media omitted>
10/22/24, 11:37 AM - Om.   Jash: <Media omitted>
10/22/24, 11:37 AM - Om.   Jash: <Media omitted>
10/22/24, 11:37 AM - Om.   Jash: <Media omitted>
10/22/24, 11:37 AM - Om.   Jash: <Media omitted>
10/22/24, 11:37 AM - Om.   Jash: <Media omitted>
10/22/24, 11:37 AM - Om.   Jash: <Media omitted>
10/22/24, 11:37 AM - Om.   Jash: <Media omitted>
10/22/24, 11:37 AM - Om.   Jash: <Media omitted>
10/22/24, 11:37 AM - Om.   Jash: <Media omitted>
10/22/24, 1:43 PM - Om.   Jash: Spearman's rank correlation : same sum krvo Rank vado
10/24/24, 10:35 AM - YASH YATIN: This message was deleted
10/24/24, 6:04 PM - Om.   Jash: <Media omitted>
10/25/24, 6:50 PM - Om.   Jash: <Media omitted>
10/25/24, 6:50 PM - Om.   Jash: <Media omitted>
10/25/24, 6:50 PM - Om.   Jash: <Media omitted>
10/25/24, 6:50 PM - Om.   Jash: <Media omitted>
10/25/24, 6:50 PM - Om.   Jash: <Media omitted>
10/25/24, 6:50 PM - Om.   Jash: <Media omitted>
10/25/24, 6:50 PM - Om.   Jash: <Media omitted>
10/25/24, 6:50 PM - Om.   Jash: <Media omitted>
10/25/24, 6:50 PM - Om.   Jash: <Media omitted>
10/27/24, 4:18 PM - devganiyaharsh: <Media omitted>
10/27/24, 4:48 PM - Balva Maulik: Are barad😅
10/27/24, 5:16 PM - Bapu: 🤣🤣
10/27/24, 5:16 PM - Himanshu: 🤣🤣🤣🤣🤣
10/27/24, 6:28 PM - Om.    Deep: 19 20 ka hi to fark hai bas 🤣😅
10/27/24, 6:29 PM - Himanshu: 🤣😂😂😂
10/27/24, 8:34 PM - Bapu: Abe chlna yar😂😂
11/12/24, 8:08 AM - YASH YATIN: <Media omitted>
11/13/24, 1:10 PM - Om Mayur: This message was deleted
11/13/24, 1:11 PM - Om Mayur: <Media omitted>
11/18/24, 1:54 PM - Om Mayur: <Media omitted>
11/18/24, 1:54 PM - Om Darshan: ?
11/18/24, 1:54 PM - Om Mayur: Maths na imp
11/18/24, 9:46 PM - Darbar: Hi
11/18/24, 9:46 PM - Darbar: Math maa koine Gama distribution sikhavu
11/18/24, 9:46 PM - Om.    Deep: Mare shikha vu
11/18/24, 9:46 PM - Darbar: Chal to bhai to online reje
11/18/24, 9:46 PM - Darbar: Okay
11/18/24, 9:47 PM - Om.    Deep: Kema
11/18/24, 9:47 PM - Om.    Deep: Instagram ma k
11/18/24, 9:47 PM - Darbar: Are bhai zoom ma
11/18/24, 9:47 PM - Om.    Deep: Aela e to nathi
11/18/24, 9:47 PM - Darbar: Aapde live session join karva no che
11/18/24, 9:47 PM - Darbar: Aetle
11/18/24, 9:47 PM - Om.    Deep: Tara phone mathi thay jav to hale k
11/18/24, 9:47 PM - Darbar: Are download kari le ne bhai
11/18/24, 9:47 PM - Om.    Deep: Net nathi
11/18/24, 9:48 PM - Om.    Deep: Tara room ma aavu jarav
11/18/24, 9:48 PM - Darbar: But mara ma tho AEK join Thai sake ne bhai
11/18/24, 9:48 PM - Om.    Deep: Loda baju ma besi Tara bhego aem kav
11/19/24, 8:43 AM - Darbar: <Media omitted>
11/19/24, 8:57 AM - Om Mayur: <Media omitted>
11/19/24, 8:57 AM - Om Mayur: <Media omitted>
11/19/24, 8:57 AM - Om Mayur: <Media omitted>
11/21/24, 9:17 AM - Om Darshan: <Media omitted>
11/26/24, 6:58 AM - Om. Jenil: <Media omitted>
11/26/24, 9:01 AM - Om Darshan: <Media omitted>
11/29/24, 9:12 AM - Om Darshan: <Media omitted>
12/3/24, 9:01 AM - Om Darshan: <Media omitted>
12/10/24, 9:01 AM - Om Darshan: <Media omitted>
12/18/24, 8:47 AM - Om Darshan: <Media omitted>
12/20/24, 12:01 PM - Om Darshan: Class room join kari lejo bhai 4th sem nu
12/20/24, 12:25 PM - Om Mayur: Ok
12/20/24, 12:25 PM - Himanshu: Ok
12/26/24, 1:20 PM - Om Darshan: <Media omitted>
12/26/24, 1:21 PM - Om Darshan: <Media omitted>
12/26/24, 1:21 PM - Om Darshan: <Media omitted>
12/26/24, 1:21 PM - Om Darshan: <Media omitted>
12/26/24, 1:21 PM - Om Darshan: <Media omitted>
12/26/24, 1:21 PM - Om Darshan: <Media omitted>
12/26/24, 1:23 PM - Bapu: Senu chhe Ela😂
12/26/24, 1:32 PM - Dilip Vaja: Kya subject nu 6
12/26/24, 1:32 PM - Om Darshan: OS
12/26/24, 1:32 PM - Om Darshan: 4th sem nu 🤣🤣🤣
12/26/24, 1:33 PM - devganiyaharsh: Payal madam le chhe
12/26/24, 1:33 PM - Bapu: 😂😂halo Aaj thi chalu preperation
12/26/24, 1:33 PM - Om.    Deep: E game e liye tare Kiya jova nu
12/26/24, 1:33 PM - Bapu: Ha e ly ley tmtare ek var tu deto khri
12/26/24, 1:33 PM - Om Darshan: Bs bhai
12/26/24, 1:33 PM - Dilip Vaja: Time table aapi didhu
12/26/24, 1:33 PM - Om Darshan: Jovu to pde ne ela
12/26/24, 1:33 PM - Om Darshan: Na
12/26/24, 1:34 PM - Om.    Deep: Ha ka aeno mal che e
12/26/24, 1:34 PM - Om Darshan: Hoy to j offer krje ho
12/26/24, 1:34 PM - Bapu: 🤣🤣
12/26/24, 1:34 PM - devganiyaharsh: Aa navu bakru kon chhe
Papa ne Sadi kare chhe
12/26/24, 1:34 PM - Bapu: Oooo
12/26/24, 1:34 PM - Bapu: 😂😂
12/26/24, 1:34 PM - Om.    Deep: Bap ko bhej tere badki nay hai 😄
12/26/24, 1:36 PM - Om.    Deep: Harshla Sachin bolavava gayo k 😄
12/26/24, 1:54 PM - devganiyaharsh: Na na l***
12/26/24, 1:54 PM - devganiyaharsh: 😅
12/26/24, 1:55 PM - Om.    Deep: De aama AEK tuj girl cho 😜
12/26/24, 2:11 PM - devganiyaharsh: Taru magaj haji chhokariyu ma j hale chhe
Thodok bar aav aema thi
Duniya jo loda
12/26/24, 2:12 PM - Om.    Deep: Loda jova mate to chama lidha
12/26/24, 2:12 PM - Bapu: Are bhos ma to tme bhrmana chho biradr
12/26/24, 2:12 PM - Bapu: 😂😂
12/26/24, 2:12 PM - Om.    Deep: Loda taru dhiyan che aema to
12/26/24, 7:11 PM - Om Mayur: <Media omitted>
1/2/25, 3:36 PM - Darbar: This message was deleted
1/2/25, 3:36 PM - Darbar: This message was deleted
1/2/25, 3:50 PM - Darbar: <Media omitted>
1/9/25, 1:40 PM - Om.   Jash: Kale OOP unit-1 ni test che
1/9/25, 1:40 PM - Om.   Jash: First 2 lectures che
1/9/25, 1:40 PM - Om Mayur: Ok
1/11/25, 1:07 PM - Om.   Jash: <Media omitted>
1/13/25, 10:09 AM - Om. Jenil: This message was deleted
1/13/25, 10:10 AM - Om. Jenil: This message was deleted
1/13/25, 1:57 PM - Om Mayur: Jenil ne personal ma moklu lage
1/13/25, 2:45 PM - Om Darshan: Hn bhai
1/13/25, 2:45 PM - Om Darshan: Sir e nath moklyu baki to ghre deva jai circular
1/13/25, 2:45 PM - Om Darshan: Jenil makarsankranti nu na moklyu! Mdm e
1/13/25, 2:45 PM - Om Mayur: True
1/13/25, 2:46 PM - Om Darshan: Ke personal ma deva aavse same same bhatkavva
1/13/25, 2:46 PM - Om Mayur: Aa mast plane che
1/14/25, 1:32 PM - Om. Jenil: Tari vaat nthi thati
1/14/25, 1:35 PM - Darbar: Happy makar Sankranti 🪁
Jenil bhai
1/14/25, 1:35 PM - Darbar: Badhavanu nay ho
1/14/25, 1:50 PM - Om Darshan: Aetle to tne kv chu same bhatkavva u kam taru che
1/14/25, 1:50 PM - Om Darshan: Hse bhai

In [64]:
print(type(data))

<class 'str'>

In [67]:
pattern = r"\d{1,2}/\d{1,2}/\d{2},\s\d{1,2}:\d{2}\s[AP]M\s-\s"

In [68]:
messages = re.split(pattern,data)[1: ]
messages

['Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. Learn more.\n',
 '~\u202fBhargav Patel created group "STUDY MATERIAL GROUP✍️"\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ added you\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ added Darbar\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: <Media omitted>\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: <Media omitted>\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: <Media omitted>\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: <Media omitted>\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: <Media omitted>\n',
 'Om.    Deep: <Media omitted>\n',
 'Om.    Deep: <Media omitted>\n',
 'Om.    Deep: <Media omitted>\n',
 'Om.    Deep: <Media omitted>\n',
 'Om.    Deep: <Media omitted>\n',
 'Om. Jenil: This message was deleted\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: This message was deleted\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: This message was deleted\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Arreeee result joy lau aavi gyuuu\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Jaldi\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Lodau\n',
 'Bapu: Kya link to mokl wedsite ne\n',
 '+91 94287 92992: Khoti chodino che\n',
 'Bapu: Avaj loda 6 aya🤣🤣\n',
 '+91 94287 92992: E j ne\n',
 'Om.    Deep: 😂\n',
 'devganiyaharsh: 😂😂😂\n',
 'Om.    Deep: Kon che\n',
 '+91 94287 92992: Rand\n',
 'Bapu: Brand🤣🤣\n',
 'Om Darshan: 🤣\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Pikina\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Loda\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Tention na lyo badha pass thay jaso lodau\n',
 'Bapu: Jane loda tu ayathi etle ame pass j 6😂😂\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Pikina\n',
 'Bapu: Apsbd ny\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Himanshu: <Media omitted>\n',
 'Himanshu: <Media omitted>\n',
 'Himanshu: <Media omitted>\n',
 'Himanshu: <Media omitted>\n',
 '+91 94287 92992: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 '+91 94287 92992: <Media omitted>\n',
 '+91 94287 92992: <Media omitted>\n',
 '+91 94287 92992: <Media omitted>\n',
 '+91 94287 92992: <Media omitted>\n',
 '+91 94287 92992: <Media omitted>\n',
 '+91 94287 92992: <Media omitted>\n',
 '+91 94287 92992: <Media omitted>\n',
 '+91 94287 92992: <Media omitted>\n',
 'Om Darshan: Kale aavana ne\n',
 'Bapu: Ha ha\n',
 'Bapu: Kal avjo badhat\n',
 'Bapu: Badhay\n',
 'Bapu: <Media omitted>\n',
 'Bapu: Ela ato bhdvay kyri aniye\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Ha yr\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Have su kar vu\n',
 'Bapu: Me phn kyroto aghdi ene\n',
 'Bapu: K tmne puuchhi ne to raykhu\n',
 'devganiyaharsh: Aene Kay hostel vala to ghare vaya gya\n',
 'Bapu: To k kal puchhva ka no ayva\n',
 'Bapu: Mne ke kal avi jav pachhi rakhi dejo\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Aene ke tu kya hato kale\n',
 'Bapu: Me ej kidhu eke phn kyro hot to\n',
 'Bapu: Mne ke aya badhay mne key k cours baki 6 ne km rja api dyo tme\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: To aene ke aaje Kari didho ne have 😁\n',
 'Bapu: Ela land 6 eye\n',
 'Bapu: Hve su krvu kal nu\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: To yr\n',
 'devganiyaharsh: Bhavala phone Kari ne ke ke hostel vala to ghare vaya gya 😂\n',
 'devganiyaharsh: Chhe\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Hn\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: M Kaik Karo to thay have\n',
 'Bapu: Ha Halo ne kyk kriye\n',
 'Bapu: Ela ek var to kyro😂\n',
 'Bapu: Ene loda ne bija upadta hoy ke aa badhay km aam rja rakhe\n',
 'Bapu: Etle\n',
 'Om.    Deep: Aaj kon kon gaya\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Koy nai 😁\n',
 'Bapu: Koy nath gyu ela\n',
 'Om.    Deep: To su koy jata nay\n',
 'devganiyaharsh: 😄😄\n',
 'devganiyaharsh: Hooop\n',
 'Bapu: 😂😂\n',
 '+91 94287 92992: Kale javanu ke nay?\n',
 'Om.    Deep: Nay\n',
 'Bapu: Na na hve thodi jvay\n',
 '+91 94287 92992: Ene phone ma su kidhu\n',
 'Om.    Deep: Jene jiya khila khod va hoy e khodi le\n',
 'Bapu: Eke kal puchhi lidhu hot to mne\n',
 '+91 94287 92992: Ane kidhu ke aavi jajo\n',
 'Om.    Deep: Aene kay AEK var to kidhu\n',
 'Bapu: Eke kal avi jajo\n',
 'Om.    Deep: Hostel vadanu kidhu to su kidhu\n',
 'Bapu: Na e nthi kidhu\n',
 '+91 94287 92992: Hostel varav kok phone kari ko ke ame su karye\n',
 'Bapu: Ha ela deepla tu phn kar\n',
 'Bapu: Ene ky ame ghre avta rya\n',
 'Om. Jenil: Su krvanu aa to ke j bhavesh\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Kevuj padche tane\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Baki nai chale\n',
 'Om. Jenil: Right 👍\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Ohhh\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Bhavesh ke se toj chal che ne\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Amaro to nai gam to\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Tane\n',
 'Om. Jenil: Badhani pela tu Leto to\n',
 'Om. Jenil: Aa dekhay j chhe 😂\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Bhavesh bol jaldi baki jenil ne kaik thay jase bhai\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Tyare bhavesh Mane ke Toto ke jenil Maro lodo mage se 😁\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: To pachi me kidhu ke aapi de aene taro j fave\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Bija koy na maja nathi aavti\n',
 'devganiyaharsh: નથી બિતા જેને જ્યાં ખીલા ખોડવા હોય nya khodi de 😂\n',
 'devganiyaharsh: Mahesh ne kyo Mahesh ne \nE boss chhe\n',
 'devganiyaharsh: 😂😂\n',
 'devganiyaharsh: Hamna phone karse e\n',
 'devganiyaharsh: E no bive ho 😂\n',
 'Om. Jenil: Aano leva gyo to m ne 😂\n',
 'Om. Jenil: Aatle tne bov kidhu 😂😂\n',
 'Om. Jenil: Bhavesh mja aavi ne brand ma 😂😂\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Have aava message nai kar to Bhai\n',
 'Om. Jenil: Chalu Kone krya\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Aaje gya ta koy ke nai ?\n',
 'devganiyaharsh: Nay bhai\n',
 'Om. Jenil: Koi nthi gyu\n',
 'devganiyaharsh: Paku ne\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Okay\n',
 'Om. Jenil: Ha\n',
 'Om. Jenil: Bhai\n',
 'devganiyaharsh: To vandho nay\n',
 'devganiyaharsh: Tu hasti chho tane to khbr j hoy ne <This message was edited>\n',
 'Bapu: 🤣🤣🤣\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Ae vatt 100 taka sachi ho\n',
 'Om ᴀ ʀ ʏ ᴀ ɴ: Jenil Seth 🖕🖕\n',
 'Om. Jenil: <Media omitted>\n',
 'Om.    Deep: Vah Jenil bhai tari pase kiyathi\n',
 'Om. Jenil: Nayan Joshi aa moklyu\n',
 'Om.    Deep: Kema group ma\n',
 'Om. Jenil: Nayan aa banvyu tu aa\n',
 'Om Mayur: Koi pase lab manual na photo hoy to mokljo\n',
 'Om. Jenil: <Media omitted>\n',
 'Om. Jenil: <Media omitted>\n',
 'devganiyaharsh: Hosiyar ho Jenil bhai\n',
 'Om. Jenil: Na Bhai\n',
 'Om. Jenil: Tmari jetla ny\n',
 'Om Mayur: Jenil nava mokalne a lakhay Gaya chhe\n',
 'Om. Jenil: Aavu chhe 😂\n',
 'Om Mayur: Pps nu homework Thai gayu\n',
 'Om Darshan: Kyu\n',
 'Om Mayur: Defination\n',
 'Om Mayur: Aecu kaik lakhavanu hatu\n',
 'Om Darshan: Na\n',
 'Om Mayur: Lab manual kya sudhi lakhavani chhe\n',
 'Om Darshan: 38\n',
 'Om Darshan: Kadach\n',
 'Om Darshan: Ka 39\n',
 'Om Mayur: Tare lakhay gaya\n',
 'Himanshu: 29,30,31,32,33,37\n',
 'Om Mayur: To maklje mane\n',
 '+91 94287 92992: Halo ff\n',
 'Om Darshan: Thodik var pachi\n',
 'Om Darshan: Kal javu ne\n',
 'Om Darshan: 😅🤣\n',
 'Om.    Deep: Kiya\n',
 'Bapu: Ye kab ho gya itna sara Bhai 🤣🤣\n',
 'Bapu: Hu to kv somvare Jaye hve😜😂\n',
 'Om Darshan: Na bhai\n',
 'Bapu: 😂😂👍\n',
 '+91 94287 92992: Recheck nu result aavi gyu\n',
 'Bapu: Hkn\n',
 'Om Mayur: Series solution \n1) classified singularity (3 or 4 mark)\n2) series solution at ordinary point (7 mark confirm)\n3) series solution at regular sigular point (7- mark confirm)\n4) bachi J 1/2 -1/2 3/2 -3/2 mathi ak example (4 mark)\n5) recrence relation no ek examples (3- mark)\n',
 'Om Mayur: First order firest degree \n1) excet diff. \n2) liner diff.\n3) Bernoulli diff.\nAa 3 method mathi 2 method confirm hse j\n',
 'Om Mayur: Baki \nSolvable for p , x and y mathi hoi aa may b option ma nikdi jai\n',
 'Om Mayur: Laplece mathi \nConvolution theorem\nPartial plfraction \n2nd shifting\nNd bdhi property no mix examples\n',
 'Om Darshan: This message was deleted\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: Hii\n',
 'Om Darshan: Hello\n',
 'Om Darshan: Internal marks joi lejo badha\n',
 '+91 94287 92992: Hi\n',
 '+91 94287 92992: Link send karjene\n',
 'Om Darshan: Google mar\n',
 'Himanshu: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om.    Deep: 8P7 WQZ 2NG\n',
 'Om Darshan: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om Mayur: This message was deleted\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: Test che\n',
 'Om Mayur: DBMS\n',
 'Om Mayur: Ha ke na\n',
 'Om Darshan: Ha syd\n',
 'Bapu: Nathi nathi\n',
 'Om Mayur: Oo\n',
 'Bapu: Nathi test ela moj kro\n',
 'Om Mayur: Ok\n',
 'Bapu: 😂😂\n',
 'YASH YATIN: Na\n',
 'Himanshu added Balva Maulik\n',
 'Darbar: <Media omitted>\n',
 'Darbar: <Media omitted>\n',
 'Darbar: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Himanshu: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Himanshu added Om. Khush\n',
 'Himanshu: <Media omitted>\n',
 'Himanshu: <Media omitted>\n',
 'Himanshu: <Media omitted>\n',
 'Himanshu: <Media omitted>\n',
 'devganiyaharsh: <Media omitted>\n',
 'Om. Khush: <Media omitted>\n',
 'Om. Khush: <Media omitted>\n',
 'Om. Khush: <Media omitted>\n',
 '+91 94287 92992: <Media omitted>\n',
 'Om. Khush: <Media omitted>\n',
 'Darbar: <Media omitted>\n',
 'Himanshu: A su che Bhai seni Tarik che\n',
 'Bapu: Gtu. Ni chhe n\n',
 'Darbar: 3 sem exam\n',
 'Himanshu: Gtu\n',
 'Himanshu: Ni\n',
 'Om Mayur: Ha\n',
 '+91 94287 92992: Sem 3 nu time table send karoto\n',
 '+91 94287 92992: All branch varu\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: Branch code joi leje ama\n',
 'Himanshu: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om Mayur: 7/11 to 19/11 submission all subjects\n',
 'Om.   Jash: Revision classs?\n',
 'Om Mayur: Kese pachi\n',
 'YASH YATIN: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 "Om.   Jash: Spearman's rank correlation : same sum krvo Rank vado\n",
 'YASH YATIN: This message was deleted\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'Om.   Jash: <Media omitted>\n',
 'devganiyaharsh: <Media omitted>\n',
 'Balva Maulik: Are barad😅\n',
 'Bapu: 🤣🤣\n',
 'Himanshu: 🤣🤣🤣🤣🤣\n',
 'Om.    Deep: 19 20 ka hi to fark hai bas 🤣😅\n',
 'Himanshu: 🤣😂😂😂\n',
 'Bapu: Abe chlna yar😂😂\n',
 'YASH YATIN: <Media omitted>\n',
 'Om Mayur: This message was deleted\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Darshan: ?\n',
 'Om Mayur: Maths na imp\n',
 'Darbar: Hi\n',
 'Darbar: Math maa koine Gama distribution sikhavu\n',
 'Om.    Deep: Mare shikha vu\n',
 'Darbar: Chal to bhai to online reje\n',
 'Darbar: Okay\n',
 'Om.    Deep: Kema\n',
 'Om.    Deep: Instagram ma k\n',
 'Darbar: Are bhai zoom ma\n',
 'Om.    Deep: Aela e to nathi\n',
 'Darbar: Aapde live session join karva no che\n',
 'Darbar: Aetle\n',
 'Om.    Deep: Tara phone mathi thay jav to hale k\n',
 'Darbar: Are download kari le ne bhai\n',
 'Om.    Deep: Net nathi\n',
 'Om.    Deep: Tara room ma aavu jarav\n',
 'Darbar: But mara ma tho AEK join Thai sake ne bhai\n',
 'Om.    Deep: Loda baju ma besi Tara bhego aem kav\n',
 'Darbar: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Mayur: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om. Jenil: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: Class room join kari lejo bhai 4th sem nu\n',
 'Om Mayur: Ok\n',
 'Himanshu: Ok\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'Bapu: Senu chhe Ela😂\n',
 'Dilip Vaja: Kya subject nu 6\n',
 'Om Darshan: OS\n',
 'Om Darshan: 4th sem nu 🤣🤣🤣\n',
 'devganiyaharsh: Payal madam le chhe\n',
 'Bapu: 😂😂halo Aaj thi chalu preperation\n',
 'Om.    Deep: E game e liye tare Kiya jova nu\n',
 'Bapu: Ha e ly ley tmtare ek var tu deto khri\n',
 'Om Darshan: Bs bhai\n',
 'Dilip Vaja: Time table aapi didhu\n',
 'Om Darshan: Jovu to pde ne ela\n',
 'Om Darshan: Na\n',
 'Om.    Deep: Ha ka aeno mal che e\n',
 'Om Darshan: Hoy to j offer krje ho\n',
 'Bapu: 🤣🤣\n',
 'devganiyaharsh: Aa navu bakru kon chhe \nPapa ne Sadi kare chhe\n',
 'Bapu: Oooo\n',
 'Bapu: 😂😂\n',
 'Om.    Deep: Bap ko bhej tere badki nay hai 😄\n',
 'Om.    Deep: Harshla Sachin bolavava gayo k 😄\n',
 'devganiyaharsh: Na na l***\n',
 'devganiyaharsh: 😅\n',
 'Om.    Deep: De aama AEK tuj girl cho 😜\n',
 'devganiyaharsh: Taru magaj haji chhokariyu ma j hale chhe \nThodok bar aav aema thi \nDuniya jo loda\n',
 'Om.    Deep: Loda jova mate to chama lidha\n',
 'Bapu: Are bhos ma to tme bhrmana chho biradr\n',
 'Bapu: 😂😂\n',
 'Om.    Deep: Loda taru dhiyan che aema to\n',
 'Om Mayur: <Media omitted>\n',
 'Darbar: This message was deleted\n',
 'Darbar: This message was deleted\n',
 'Darbar: <Media omitted>\n',
 'Om.   Jash: Kale OOP unit-1 ni test che\n',
 'Om.   Jash: First 2 lectures che\n',
 'Om Mayur: Ok\n',
 'Om.   Jash: <Media omitted>\n',
 'Om. Jenil: This message was deleted\n',
 'Om. Jenil: This message was deleted\n',
 'Om Mayur: Jenil ne personal ma moklu lage\n',
 'Om Darshan: Hn bhai\n',
 'Om Darshan: Sir e nath moklyu baki to ghre deva jai circular\n',
 'Om Darshan: Jenil makarsankranti nu na moklyu! Mdm e\n',
 'Om Mayur: True\n',
 'Om Darshan: Ke personal ma deva aavse same same bhatkavva\n',
 'Om Mayur: Aa mast plane che\n',
 'Om. Jenil: Tari vaat nthi thati\n',
 'Darbar: Happy makar Sankranti 🪁 \nJenil bhai\n',
 'Darbar: Badhavanu nay ho\n',
 'Om Darshan: Aetle to tne kv chu same bhatkavva u kam taru che\n',
 'Om Darshan: Hse bhai\n',
 'Om Darshan: Aatlo late reply aela 2 di thi bhatkave su stemina che hse hse\n',
 'Om Darshan: Moj m ne\n',
 'Om. Jenil: Tara Kam ma Maru naam no devay\n',
 'Om. Jenil: Kal no j msg chhe\n',
 'Om Darshan: Aela tne dav chu tara name ne ni\n',
 'Om Darshan: Hn ej ne kale nvro ni ho tu aetle to aaje reply didho\n',
 'Om Darshan: Om pn bhatkavva ma time n male ne tne\n',
 'Om Darshan: This message was deleted\n',
 'Om. Jenil: Bhatkava nu Kam to taru chhe\n',
 'Om Darshan: Na bhai amari pase to che\n',
 'Om. Jenil: Mari pase pn chhe bhai <This message was edited>\n',
 'Om Darshan: Su\n',
 'Om Darshan: Aela e muk tu e\n',
 'Om. Jenil: Ok\n',
 'Om. Jenil: Kal nu su chhe\n',
 'Om Darshan: Javanu su hoy\n',
 'Om. Jenil: Nthi javanu\n',
 'Om. Jenil: ?\n',
 'Om Darshan: Aela e javanu che\n',
 'Om. Jenil: To bhale\n',
 'Dilip Vaja: Jenil ne to aavu j pade ene personal ma message karyo hato\n',
 'Om Darshan: Hn yr e pn che\n',
 'YASH YATIN: <Media omitted>\n',
 'Om.   Jash: Bhai log ,\n \nKale 2-4 cricket ramvanu che\n',
 'Om Darshan: Okie\n',
 'Om.   Jash: Etle kale KheloOm ma j team ma hoi e 2-4 rejo\n',
 'Om.   Jash: Ha m\n',
 'Himanshu: <Media omitted>\n',
 'Himanshu: <Media omitted>\n',
 'YASH YATIN: <Media omitted>\n',
 'Om Darshan: <Media omitted>\n',
 'YASH YATIN: <Media omitted>\n',
 'Om.    Deep: Loda aatiyare hoy kay aavu\n',
 'YASH YATIN: Sorry bhai\n',
 'YASH YATIN: Ke to delete kari nakhu\n',
 'Om.    Deep: Na bhai 😂\n',
 'YASH YATIN: Ok\n',
 'YASH YATIN: This message was deleted\n',
 'Om. Khush: <Media omitted>\n',
 'Balva Maulik: 🤣🤣\n',
 'Om. Khush: <Media omitted>\n',
 'Om. Khush: <Media omitted>\n',
 'Om. Khush: Leave application format\n',
 'YASH YATIN: This message was deleted\n',
 'YASH YATIN: This message was deleted\n',
 'Om.   Jash: <Media omitted>\n',
 "Om. Jenil: It looks like you're asking whether \\((\\mathbb{Z}_5, \\mathbb{X}_6)\\) is cyclic. However, the notation \\(\\mathbb{X}_6\\) is unclear. If you meant the multiplicative group of units modulo 6, denoted as \\(\\mathbb{Z}_6^\\times\\), let's analyze it.\n\n### Step 1: Understanding the Structure of \\((\\mathbb{Z}_5, \\mathbb{Z}_6^\\times)\\)\n- \\(\\mathbb{Z}_5 = \\{0,1,2,3,4\\}\\) is the additive cyclic group of integers modulo 5.\n- \\(\\mathbb{Z}_6^\\times = \\{1,5\\}\\) is the multiplicative group of units modulo 6. These are the integers that are coprime to 6 under multiplication mod 6.\n\n### Step 2: Orders of the Groups\n- \\(\\mathbb{Z}_5\\) is a cyclic group of order 5.\n- \\(\\mathbb{Z}_6^\\times = \\{1, 5\\}\\) is a cyclic group of order 2 (since \\(5^2 \\equiv 1 \\mod 6\\)).\n\n### Step 3: Direct Product and Cyclicity\nThe order of \\((\\mathbb{Z}_5, \\mathbb{Z}_6^\\times)\\) is:\n\\[\n|\\mathbb{Z}_5| \\times |\\mathbb{Z}_6^\\times| = 5 \\times 2 = 10.\n\\]\nA direct product of two cyclic groups \\(\\mathbb{Z}_m\\) and \\(\\mathbb{Z}_n\\) is cyclic if and only if \\(\\gcd(m, n) = 1\\).\n\nSince \\(\\gcd(5,2) = 1\\), the group \\((\\mathbb{Z}_5, \\mathbb{Z}_6^\\times)\\) is cyclic of order 10.\n\n### Step 4: Finding a Generator\nA generator \\((a, b)\\) should have order 10, meaning the least \\( k \\) for which:\n\\[\n(k a \\mod 5, k b \\mod 6) = (0,1).\n\\]\nTaking \\((1,5)\\):\n- The order of 1 in \\(\\mathbb{Z}_5\\) is 5.\n- The order of 5 in \\(\\mathbb{Z}_6^\\times\\) is 2.\n- The least common multiple of 5 and 2 is:\n  \\[\n  \\operatorname{lcm}(5,2) = 10.\n  \\]\nThus, \\((1,5)\\) generates the entire group.\n\n### Conclusion\nSince we found a generator of order 10, \\((\\mathbb{Z}_5, \\mathbb{Z}_6^\\times)\\) is a cyclic group.\n",
 'Om. Jenil: Cyclic group show that (z5,X6)\n',
 'YASH YATIN: https://gtunewooppracticals.blogspot.com/\n',
 'YASH YATIN: Oop manual\n',
 'devganiyaharsh: <Media omitted>\n',
 'devganiyaharsh: <Media omitted>\n',
 'devganiyaharsh: <Media omitted>\n',
 'Om. Jenil: This message was deleted\n',
 'Om.    Deep: <Media omitted>\n',
 'Om.    Deep: Chatgpt no sacho upayog\n',
 'Darbar: This message was deleted\n',
 'Om.    Deep: Jane chodu\n',
 'Darbar: This message was deleted\n',
 'Om.    Deep: Bhosado ne e rate\n',
 'Dilip Vaja: <Media omitted>\n',
 'Dilip Vaja: Result aavi gyu\n',
 'Om.    Deep: Ha aela\n',
 'Om.    Deep: Gand fati gay\n',
 'YASH YATIN: This message was deleted\n',
 'YASH YATIN: This message was deleted\n',
 'YASH YATIN: This message was deleted\n',
 'Om.    Deep: Aela aavi gayu\n',
 'Om.    Deep: Masti nay aavi gayu\n',
 'YASH YATIN: This message was deleted\n',
 'Om.    Deep: Mare 2 ma aayvi\n',
 'Om. Jenil: Edited chhe\n',
 'Om. Khush: <Media omitted>\n',
 'devganiyaharsh: <Media omitted>\n',
 'devganiyaharsh: <Media omitted>\n',
 'devganiyaharsh: <Media omitted>\n',
 'Om. Khush added Om Harshad\n',
 'Om Darshan: Hiii\n',
 'Om Darshan: Bhai result joi lejo\n',
 'Om.    Deep: <Media omitted>\n',
 'Om.    Deep: Be ma lode lagi gaya\n',
 'Om.    Deep: Hu AEK j fail chu k 🤣\n',
 'Darbar: Are evu nathi\n',
 'Darbar: Badha bayu hare vatu karavama se\n',
 'Om Mayur: Are evu nathi\n',
 'Darbar: To mokar results\n',
 'Om.    Deep: Mayur tare su che\n',
 'Dilip Vaja: This message was deleted\n',
 'Om Mayur: Website nathi khulti mare\n',
 'Om.    Deep: Password de hu joy dav\n',
 'Darbar: Jaldi\n',
 'Darbar: Jenil kya gayo\n',

In [69]:
dates = re.findall(pattern,data)
dates

['3/15/24, 10:40\u202fAM - ',
 '10/11/23, 1:27\u202fPM - ',
 '3/15/24, 10:40\u202fAM - ',
 '3/15/24, 10:40\u202fAM - ',
 '3/15/24, 12:22\u202fPM - ',
 '3/15/24, 12:22\u202fPM - ',
 '3/15/24, 12:22\u202fPM - ',
 '3/15/24, 12:22\u202fPM - ',
 '3/15/24, 12:22\u202fPM - ',
 '3/15/24, 12:24\u202fPM - ',
 '3/15/24, 12:24\u202fPM - ',
 '3/15/24, 12:24\u202fPM - ',
 '3/15/24, 12:24\u202fPM - ',
 '3/15/24, 12:24\u202fPM - ',
 '3/16/24, 10:38\u202fAM - ',
 '3/16/24, 10:38\u202fAM - ',
 '3/16/24, 10:38\u202fAM - ',
 '3/31/24, 11:58\u202fAM - ',
 '3/31/24, 11:58\u202fAM - ',
 '3/31/24, 11:58\u202fAM - ',
 '3/31/24, 12:03\u202fPM - ',
 '3/31/24, 12:03\u202fPM - ',
 '3/31/24, 12:03\u202fPM - ',
 '3/31/24, 12:04\u202fPM - ',
 '3/31/24, 12:04\u202fPM - ',
 '3/31/24, 12:04\u202fPM - ',
 '3/31/24, 12:04\u202fPM - ',
 '3/31/24, 12:04\u202fPM - ',
 '3/31/24, 12:04\u202fPM - ',
 '3/31/24, 12:04\u202fPM - ',
 '3/31/24, 12:06\u202fPM - ',
 '3/31/24, 12:07\u202fPM - ',
 '3/31/24, 12:07\u202fPM - ',
 '3/31/24, 12:08\u202fPM - ',
 '3/31/24, 12:08\u202fPM - ',
 '3/31/24, 12:08\u202fPM - ',
 '4/10/24, 10:01\u202fAM - ',
 '4/10/24, 10:01\u202fAM - ',
 '4/10/24, 10:01\u202fAM - ',
 '4/10/24, 10:01\u202fAM - ',
 '4/10/24, 10:01\u202fAM - ',
 '4/10/24, 10:01\u202fAM - ',
 '4/10/24, 10:01\u202fAM - ',
 '4/10/24, 11:11\u202fAM - ',
 '4/10/24, 11:16\u202fAM - ',
 '4/10/24, 11:16\u202fAM - ',
 '4/10/24, 11:16\u202fAM - ',
 '4/10/24, 11:16\u202fAM - ',
 '4/10/24, 11:16\u202fAM - ',
 '4/10/24, 11:16\u202fAM - ',
 '4/10/24, 11:16\u202fAM - ',
 '4/12/24, 12:47\u202fPM - ',
 '4/12/24, 12:48\u202fPM - ',
 '4/12/24, 12:48\u202fPM - ',
 '4/12/24, 12:48\u202fPM - ',
 '4/12/24, 12:48\u202fPM - ',
 '4/13/24, 11:26\u202fAM - ',
 '4/25/24, 9:41\u202fAM - ',
 '4/25/24, 9:41\u202fAM - ',
 '4/25/24, 9:41\u202fAM - ',
 '4/25/24, 9:41\u202fAM - ',
 '4/25/24, 9:41\u202fAM - ',
 '4/25/24, 9:41\u202fAM - ',
 '4/25/24, 9:41\u202fAM - ',
 '4/25/24, 9:41\u202fAM - ',
 '4/28/24, 11:22\u202fAM - ',
 '4/28/24, 11:23\u202fAM - ',
 '4/28/24, 11:23\u202fAM - ',
 '4/28/24, 11:23\u202fAM - ',
 '5/2/24, 8:21\u202fAM - ',
 '5/2/24, 8:21\u202fAM - ',
 '5/2/24, 8:21\u202fAM - ',
 '5/2/24, 8:22\u202fAM - ',
 '5/2/24, 8:22\u202fAM - ',
 '5/2/24, 8:22\u202fAM - ',
 '5/2/24, 8:22\u202fAM - ',
 '5/2/24, 8:22\u202fAM - ',
 '5/2/24, 8:22\u202fAM - ',
 '5/2/24, 8:22\u202fAM - ',
 '5/2/24, 8:23\u202fAM - ',
 '5/2/24, 8:23\u202fAM - ',
 '5/2/24, 8:23\u202fAM - ',
 '5/2/24, 8:23\u202fAM - ',
 '5/2/24, 8:23\u202fAM - ',
 '5/2/24, 8:23\u202fAM - ',
 '5/2/24, 8:25\u202fAM - ',
 '5/2/24, 8:25\u202fAM - ',
 '5/2/24, 8:25\u202fAM - ',
 '5/2/24, 8:26\u202fAM - ',
 '5/2/24, 8:27\u202fAM - ',
 '5/2/24, 8:27\u202fAM - ',
 '5/2/24, 8:28\u202fAM - ',
 '5/2/24, 8:28\u202fAM - ',
 '5/2/24, 8:28\u202fAM - ',
 '5/2/24, 8:28\u202fAM - ',
 '5/2/24, 8:29\u202fAM - ',
 '5/2/24, 8:29\u202fAM - ',
 '5/2/24, 8:29\u202fAM - ',
 '5/2/24, 8:30\u202fAM - ',
 '5/2/24, 8:30\u202fAM - ',
 '5/2/24, 8:41\u202fAM - ',
 '5/2/24, 8:41\u202fAM - ',
 '5/2/24, 8:41\u202fAM - ',
 '5/2/24, 8:41\u202fAM - ',
 '5/2/24, 8:41\u202fAM - ',
 '5/2/24, 8:42\u202fAM - ',
 '5/2/24, 8:42\u202fAM - ',
 '5/2/24, 8:42\u202fAM - ',
 '5/2/24, 8:42\u202fAM - ',
 '5/2/24, 8:43\u202fAM - ',
 '5/2/24, 8:43\u202fAM - ',
 '5/2/24, 8:43\u202fAM - ',
 '5/2/24, 8:44\u202fAM - ',
 '5/2/24, 8:44\u202fAM - ',
 '5/2/24, 9:05\u202fAM - ',
 '5/2/24, 9:06\u202fAM - ',
 '5/2/24, 9:06\u202fAM - ',
 '5/2/24, 9:06\u202fAM - ',
 '5/2/24, 9:06\u202fAM - ',
 '5/2/24, 9:07\u202fAM - ',
 '5/2/24, 9:07\u202fAM - ',
 '5/2/24, 9:07\u202fAM - ',
 '5/2/24, 9:07\u202fAM - ',
 '5/2/24, 9:07\u202fAM - ',
 '5/2/24, 9:07\u202fAM - ',
 '5/2/24, 9:08\u202fAM - ',
 '5/2/24, 9:08\u202fAM - ',
 '5/2/24, 9:09\u202fAM - ',
 '5/2/24, 9:18\u202fAM - ',
 '5/2/24, 9:19\u202fAM - ',
 '5/2/24, 9:21\u202fAM - ',
 '5/2/24, 9:21\u202fAM - ',
 '5/2/24, 9:21\u202fAM - ',
 '5/2/24, 10:01\u202fAM - ',
 '5/2/24, 10:01\u202fAM - ',
 '5/2/24, 10:02\u202fAM - ',
 '5/2/24, 10:05\u202fAM - ',
 '5/2/24, 10:05\u202fAM - ',
 '5/3/24, 4:46\u202fPM - ',
 '5/3/24, 4:51\u202fPM - ',
 '5/3/24, 5:14\u202fPM - ',
 '5/3/24, 5:23\u202fPM - ',
 '5/3/24, 5:32\u202fPM - ',
 '5/3/24, 5:35\u202fPM - ',
 '5/3/24, 5:35\u202fPM - ',
 '5/3/24, 8:13\u202fPM - ',
 '5/3/24, 8:13\u202fPM - ',
 '5/3/24, 8:15\u202fPM - ',
 '5/3/24, 9:09\u202fPM - ',
 '5/3/24, 9:09\u202fPM - ',
 '5/4/24, 1:44\u202fPM - ',
 '5/4/24, 2:01\u202fPM - ',
 '5/4/24, 2:21\u202fPM - ',
 '5/4/24, 2:22\u202fPM - ',
 '5/4/24, 4:39\u202fPM - ',
 '5/7/24, 12:03\u202fPM - ',
 '5/7/24, 12:51\u202fPM - ',
 '5/7/24, 12:51\u202fPM - ',
 '5/7/24, 1:15\u202fPM - ',
 '5/7/24, 1:28\u202fPM - ',
 '5/7/24, 1:29\u202fPM - ',
 '5/7/24, 2:30\u202fPM - ',
 '5/7/24, 2:37\u202fPM - ',
 '5/7/24, 5:30\u202fPM - ',
 '5/7/24, 5:30\u202fPM - ',
 '5/7/24, 5:30\u202fPM - ',
 '5/7/24, 5:30\u202fPM - ',
 '5/7/24, 5:30\u202fPM - ',
 '5/7/24, 5:31\u202fPM - ',
 '5/7/24, 5:34\u202fPM - ',
 '5/7/24, 5:34\u202fPM - ',
 '5/7/24, 5:34\u202fPM - ',
 '5/7/24, 5:34\u202fPM - ',
 '5/7/24, 5:35\u202fPM - ',
 '5/7/24, 5:35\u202fPM - ',
 '5/7/24, 5:36\u202fPM - ',
 '5/7/24, 5:37\u202fPM - ',
 '5/7/24, 7:37\u202fPM - ',
 '5/7/24, 7:37\u202fPM - ',
 '5/7/24, 7:39\u202fPM - ',
 '5/7/24, 8:05\u202fPM - ',
 '5/7/24, 8:05\u202fPM - ',
 '5/7/24, 8:30\u202fPM - ',
 '5/7/24, 8:32\u202fPM - ',
 '5/9/24, 3:48\u202fPM - ',
 '5/9/24, 4:22\u202fPM - ',
 '6/3/24, 2:02\u202fPM - ',
 '6/3/24, 2:02\u202fPM - ',
 '6/3/24, 2:02\u202fPM - ',
 '6/3/24, 2:02\u202fPM - ',
 '6/3/24, 2:07\u202fPM - ',
 '6/4/24, 9:15\u202fAM - ',
 '7/16/24, 9:58\u202fAM - ',
 '7/16/24, 9:58\u202fAM - ',
 '7/16/24, 9:58\u202fAM - ',
 '7/16/24, 9:58\u202fAM - ',
 '7/16/24, 9:58\u202fAM - ',
 '7/16/24, 10:00\u202fAM - ',
 '7/30/24, 12:10\u202fPM - ',
 '8/1/24, 12:20\u202fPM - ',
 '8/1/24, 12:20\u202fPM - ',
 '8/2/24, 12:38\u202fPM - ',
 '8/8/24, 10:52\u202fAM - ',
 '8/12/24, 1:48\u202fPM - ',
 '8/30/24, 12:59\u202fPM - ',
 '9/2/24, 5:05\u202fPM - ',
 '9/2/24, 5:07\u202fPM - ',
 '9/2/24, 5:09\u202fPM - ',
 '9/2/24, 5:09\u202fPM - ',
 '9/2/24, 5:09\u202fPM - ',
 '9/2/24, 5:10\u202fPM - ',
 '9/2/24, 5:10\u202fPM - ',
 '9/2/24, 5:10\u202fPM - ',
 '9/2/24, 5:10\u202fPM - ',
 '9/2/24, 5:10\u202fPM - ',
 '9/2/24, 5:10\u202fPM - ',
 '9/2/24, 5:10\u202fPM - ',
 '9/2/24, 5:10\u202fPM - ',
 '9/2/24, 5:10\u202fPM - ',
 '9/2/24, 5:11\u202fPM - ',
 '9/2/24, 5:11\u202fPM - ',
 '9/12/24, 6:28\u202fAM - ',
 '9/12/24, 6:28\u202fAM - ',
 '9/12/24, 6:28\u202fAM - ',
 '9/12/24, 6:43\u202fAM - ',
 '9/12/24, 7:10\u202fAM - ',
 '9/12/24, 7:10\u202fAM - ',
 '9/12/24, 7:11\u202fAM - ',
 '9/12/24, 7:11\u202fAM - ',
 '9/12/24, 7:11\u202fAM - ',
 '9/12/24, 9:54\u202fAM - ',
 '9/13/24, 9:17\u202fAM - ',
 '9/13/24, 10:02\u202fAM - ',
 '9/13/24, 10:02\u202fAM - ',
 '9/13/24, 10:02\u202fAM - ',
 '9/14/24, 1:51\u202fPM - ',
 '9/30/24, 1:06\u202fPM - ',
 '10/8/24, 10:53\u202fAM - ',
 '10/8/24, 10:53\u202fAM - ',
 '10/8/24, 10:53\u202fAM - ',
 '10/8/24, 11:48\u202fAM - ',
 '10/8/24, 11:48\u202fAM - ',
 '10/8/24, 11:48\u202fAM - ',
 '10/8/24, 11:48\u202fAM - ',
 '10/9/24, 12:47\u202fPM - ',
 '10/10/24, 1:49\u202fPM - ',
 '10/14/24, 1:00\u202fPM - ',
 '10/14/24, 1:00\u202fPM - ',
 '10/15/24, 11:22\u202fAM - ',
 '10/15/24, 11:46\u202fAM - ',
 '10/17/24, 1:37\u202fPM - ',
 '10/17/24, 1:39\u202fPM - ',
 '10/17/24, 1:39\u202fPM - ',
 '10/17/24, 1:40\u202fPM - ',
 '10/17/24, 1:40\u202fPM - ',
 '10/17/24, 1:40\u202fPM - ',
 '10/17/24, 1:42\u202fPM - ',
 '10/17/24, 1:44\u202fPM - ',
 '10/17/24, 1:44\u202fPM - ',
 '10/17/24, 2:02\u202fPM - ',
 '10/17/24, 2:02\u202fPM - ',
 '10/18/24, 10:02\u202fAM - ',
 '10/18/24, 6:16\u202fPM - ',
 '10/18/24, 6:16\u202fPM - ',
 '10/18/24, 6:16\u202fPM - ',
 '10/18/24, 6:16\u202fPM - ',
 '10/18/24, 6:16\u202fPM - ',
 '10/18/24, 6:16\u202fPM - ',
 '10/19/24, 1:54\u202fPM - ',
 '10/19/24, 2:23\u202fPM - ',
 '10/19/24, 2:24\u202fPM - ',
 '10/20/24, 3:29\u202fPM - ',
 '10/21/24, 3:34\u202fPM - ',
 '10/22/24, 11:37\u202fAM - ',
 '10/22/24, 11:37\u202fAM - ',
 '10/22/24, 11:37\u202fAM - ',
 '10/22/24, 11:37\u202fAM - ',
 '10/22/24, 11:37\u202fAM - ',
 '10/22/24, 11:37\u202fAM - ',
 '10/22/24, 11:37\u202fAM - ',
 '10/22/24, 11:37\u202fAM - ',
 '10/22/24, 11:37\u202fAM - ',
 '10/22/24, 11:37\u202fAM - ',
 '10/22/24, 1:43\u202fPM - ',
 '10/24/24, 10:35\u202fAM - ',
 '10/24/24, 6:04\u202fPM - ',
 '10/25/24, 6:50\u202fPM - ',
 '10/25/24, 6:50\u202fPM - ',
 '10/25/24, 6:50\u202fPM - ',
 '10/25/24, 6:50\u202fPM - ',
 '10/25/24, 6:50\u202fPM - ',
 '10/25/24, 6:50\u202fPM - ',
 '10/25/24, 6:50\u202fPM - ',
 '10/25/24, 6:50\u202fPM - ',
 '10/25/24, 6:50\u202fPM - ',
 '10/27/24, 4:18\u202fPM - ',
 '10/27/24, 4:48\u202fPM - ',
 '10/27/24, 5:16\u202fPM - ',
 '10/27/24, 5:16\u202fPM - ',
 '10/27/24, 6:28\u202fPM - ',
 '10/27/24, 6:29\u202fPM - ',
 '10/27/24, 8:34\u202fPM - ',
 '11/12/24, 8:08\u202fAM - ',
 '11/13/24, 1:10\u202fPM - ',
 '11/13/24, 1:11\u202fPM - ',
 '11/18/24, 1:54\u202fPM - ',
 '11/18/24, 1:54\u202fPM - ',
 '11/18/24, 1:54\u202fPM - ',
 '11/18/24, 9:46\u202fPM - ',
 '11/18/24, 9:46\u202fPM - ',
 '11/18/24, 9:46\u202fPM - ',
 '11/18/24, 9:46\u202fPM - ',
 '11/18/24, 9:46\u202fPM - ',
 '11/18/24, 9:47\u202fPM - ',
 '11/18/24, 9:47\u202fPM - ',
 '11/18/24, 9:47\u202fPM - ',
 '11/18/24, 9:47\u202fPM - ',
 '11/18/24, 9:47\u202fPM - ',
 '11/18/24, 9:47\u202fPM - ',
 '11/18/24, 9:47\u202fPM - ',
 '11/18/24, 9:47\u202fPM - ',
 '11/18/24, 9:47\u202fPM - ',
 '11/18/24, 9:48\u202fPM - ',
 '11/18/24, 9:48\u202fPM - ',
 '11/18/24, 9:48\u202fPM - ',
 '11/19/24, 8:43\u202fAM - ',
 '11/19/24, 8:57\u202fAM - ',
 '11/19/24, 8:57\u202fAM - ',
 '11/19/24, 8:57\u202fAM - ',
 '11/21/24, 9:17\u202fAM - ',
 '11/26/24, 6:58\u202fAM - ',
 '11/26/24, 9:01\u202fAM - ',
 '11/29/24, 9:12\u202fAM - ',
 '12/3/24, 9:01\u202fAM - ',
 '12/10/24, 9:01\u202fAM - ',
 '12/18/24, 8:47\u202fAM - ',
 '12/20/24, 12:01\u202fPM - ',
 '12/20/24, 12:25\u202fPM - ',
 '12/20/24, 12:25\u202fPM - ',
 '12/26/24, 1:20\u202fPM - ',
 '12/26/24, 1:21\u202fPM - ',
 '12/26/24, 1:21\u202fPM - ',
 '12/26/24, 1:21\u202fPM - ',
 '12/26/24, 1:21\u202fPM - ',
 '12/26/24, 1:21\u202fPM - ',
 '12/26/24, 1:23\u202fPM - ',
 '12/26/24, 1:32\u202fPM - ',
 '12/26/24, 1:32\u202fPM - ',
 '12/26/24, 1:32\u202fPM - ',
 '12/26/24, 1:33\u202fPM - ',
 '12/26/24, 1:33\u202fPM - ',
 '12/26/24, 1:33\u202fPM - ',
 '12/26/24, 1:33\u202fPM - ',
 '12/26/24, 1:33\u202fPM - ',
 '12/26/24, 1:33\u202fPM - ',
 '12/26/24, 1:33\u202fPM - ',
 '12/26/24, 1:33\u202fPM - ',
 '12/26/24, 1:34\u202fPM - ',
 '12/26/24, 1:34\u202fPM - ',
 '12/26/24, 1:34\u202fPM - ',
 '12/26/24, 1:34\u202fPM - ',
 '12/26/24, 1:34\u202fPM - ',
 '12/26/24, 1:34\u202fPM - ',
 '12/26/24, 1:34\u202fPM - ',
 '12/26/24, 1:36\u202fPM - ',
 '12/26/24, 1:54\u202fPM - ',
 '12/26/24, 1:54\u202fPM - ',
 '12/26/24, 1:55\u202fPM - ',
 '12/26/24, 2:11\u202fPM - ',
 '12/26/24, 2:12\u202fPM - ',
 '12/26/24, 2:12\u202fPM - ',
 '12/26/24, 2:12\u202fPM - ',
 '12/26/24, 2:12\u202fPM - ',
 '12/26/24, 7:11\u202fPM - ',
 '1/2/25, 3:36\u202fPM - ',
 '1/2/25, 3:36\u202fPM - ',
 '1/2/25, 3:50\u202fPM - ',
 '1/9/25, 1:40\u202fPM - ',
 '1/9/25, 1:40\u202fPM - ',
 '1/9/25, 1:40\u202fPM - ',
 '1/11/25, 1:07\u202fPM - ',
 '1/13/25, 10:09\u202fAM - ',
 '1/13/25, 10:10\u202fAM - ',
 '1/13/25, 1:57\u202fPM - ',
 '1/13/25, 2:45\u202fPM - ',
 '1/13/25, 2:45\u202fPM - ',
 '1/13/25, 2:45\u202fPM - ',
 '1/13/25, 2:45\u202fPM - ',
 '1/13/25, 2:46\u202fPM - ',
 '1/13/25, 2:46\u202fPM - ',
 '1/14/25, 1:32\u202fPM - ',
 '1/14/25, 1:35\u202fPM - ',
 '1/14/25, 1:35\u202fPM - ',
 '1/14/25, 1:50\u202fPM - ',
 '1/14/25, 1:50\u202fPM - ',
 '1/14/25, 1:51\u202fPM - ',
 '1/14/25, 1:51\u202fPM - ',
 '1/14/25, 7:39\u202fPM - ',
 '1/14/25, 7:40\u202fPM - ',
 '1/14/25, 7:46\u202fPM - ',
 '1/14/25, 7:47\u202fPM - ',
 '1/14/25, 7:47\u202fPM - ',
 '1/14/25, 8:19\u202fPM - ',
 '1/14/25, 8:29\u202fPM - ',
 '1/14/25, 8:30\u202fPM - ',
 '1/14/25, 8:30\u202fPM - ',
 '1/14/25, 8:31\u202fPM - ',
 '1/14/25, 8:31\u202fPM - ',
 '1/14/25, 8:31\u202fPM - ',
 '1/14/25, 8:31\u202fPM - ',
 '1/14/25, 8:31\u202fPM - ',
 '1/14/25, 8:32\u202fPM - ',
 '1/14/25, 8:32\u202fPM - ',
 '1/14/25, 8:32\u202fPM - ',
 '1/14/25, 8:32\u202fPM - ',
 '1/14/25, 8:35\u202fPM - ',
 '1/14/25, 8:37\u202fPM - ',
 '1/15/25, 5:06\u202fPM - ',
 '1/16/25, 2:25\u202fPM - ',
 '1/16/25, 2:25\u202fPM - ',
 '1/16/25, 2:25\u202fPM - ',
 '1/16/25, 2:26\u202fPM - ',
 '1/21/25, 8:28\u202fAM - ',
 '1/21/25, 8:28\u202fAM - ',
 '1/21/25, 4:28\u202fPM - ',
 '1/28/25, 10:11\u202fAM - ',
 '2/7/25, 10:48\u202fPM - ',
 '2/7/25, 10:49\u202fPM - ',
 '2/7/25, 10:50\u202fPM - ',
 '2/7/25, 10:50\u202fPM - ',
 '2/7/25, 10:50\u202fPM - ',
 '2/7/25, 10:50\u202fPM - ',
 '2/8/25, 10:52\u202fAM - ',
 '2/10/25, 1:29\u202fPM - ',
 '2/10/25, 3:15\u202fPM - ',
 '2/13/25, 9:12\u202fAM - ',
 '2/13/25, 2:01\u202fPM - ',
 '2/13/25, 2:01\u202fPM - ',
 '2/17/25, 5:52\u202fPM - ',
 '2/17/25, 5:53\u202fPM - ',
 '2/18/25, 8:17\u202fAM - ',
 '2/18/25, 10:58\u202fAM - ',
 '2/18/25, 11:00\u202fAM - ',
 '2/20/25, 8:10\u202fAM - ',
 '2/20/25, 8:10\u202fAM - ',
 '2/20/25, 8:40\u202fAM - ',
 '2/20/25, 8:40\u202fAM - ',
 '2/20/25, 8:40\u202fAM - ',
 '2/20/25, 9:42\u202fAM - ',
 '2/24/25, 5:14\u202fPM - ',
 '2/24/25, 5:16\u202fPM - ',
 '2/24/25, 5:22\u202fPM - ',
 '2/24/25, 5:22\u202fPM - ',
 '2/24/25, 5:22\u202fPM - ',
 '2/24/25, 5:23\u202fPM - ',
 '2/24/25, 5:42\u202fPM - ',
 '2/24/25, 5:42\u202fPM - ',
 '2/24/25, 5:43\u202fPM - ',
 '2/24/25, 5:43\u202fPM - ',
 '2/24/25, 5:45\u202fPM - ',
 '2/24/25, 5:45\u202fPM - ',
 '2/24/25, 5:45\u202fPM - ',
 '2/24/25, 5:45\u202fPM - ',
 '2/24/25, 5:45\u202fPM - ',
 '2/24/25, 5:46\u202fPM - ',
 '2/24/25, 5:47\u202fPM - ',
 '2/24/25, 9:49\u202fPM - ',
 '2/24/25, 9:52\u202fPM - ',
 '2/27/25, 8:45\u202fAM - ',
 '2/27/25, 8:45\u202fAM - ',
 '2/27/25, 8:45\u202fAM - ',
 '2/27/25, 8:46\u202fAM - ',
 '3/1/25, 3:06\u202fPM - ',
 '3/1/25, 3:06\u202fPM - ',
 '3/1/25, 3:07\u202fPM - ',
 '3/1/25, 3:07\u202fPM - ',
 '3/1/25, 3:25\u202fPM - ',
 '3/1/25, 3:26\u202fPM - ',
 '3/1/25, 3:26\u202fPM - ',
 '3/1/25, 3:26\u202fPM - ',
 '3/1/25, 3:26\u202fPM - ',
 '3/1/25, 3:27\u202fPM - ',
 '3/1/25, 3:27\u202fPM - ',
 '3/1/25, 3:27\u202fPM - ',
 '3/1/25, 3:27\u202fPM - ',
 '3/1/25, 3:27\u202fPM - ',
 '3/1/25, 3:28\u202fPM - ',
 '3/1/25, 3:28\u202fPM - ',
 '3/1/25, 3:28\u202fPM - ',
 '3/1/25, 3:28\u202fPM - ',
 '3/1/25, 3:28\u202fPM - ',
 '3/1/25, 3:29\u202fPM - ',
 '3/1/25, 3:32\u202fPM - ',
 '3/1/25, 4:37\u202fPM - ',
 '3/1/25, 4:38\u202fPM - ',
 '3/1/25, 4:40\u202fPM - ',
 '3/1/25, 4:40\u202fPM - ',
 '3/5/25, 4:18\u202fPM - ',
 '3/5/25, 4:18\u202fPM - ',
 '3/5/25, 4:55\u202fPM - ',
 '3/5/25, 5:57\u202fPM - ',
 '3/5/25, 7:00\u202fPM - ',
 '3/5/25, 7:02\u202fPM - ',
 '3/6/25, 8:33\u202fAM - ',
 '3/6/25, 8:33\u202fAM - ',
 '3/6/25, 8:33\u202fAM - ',
 '3/6/25, 8:33\u202fAM - ',
 '3/6/25, 8:33\u202fAM - ',
 '3/13/25, 7:02\u202fPM - ',
 '3/14/25, 12:57\u202fAM - ',
 '3/15/25, 1:47\u202fPM - ',
 '3/15/25, 1:47\u202fPM - ',
 '3/15/25, 1:48\u202fPM - ',
 '3/15/25, 1:48\u202fPM - ',
 '3/15/25, 1:48\u202fPM - ',
 '3/15/25, 1:49\u202fPM - ',
 '3/15/25, 1:49\u202fPM - ',
 '3/15/25, 1:49\u202fPM - ',
 '3/15/25, 2:25\u202fPM - ',
 '3/26/25, 8:02\u202fAM - ',
 '3/26/25, 8:02\u202fAM - ',
 '3/26/25, 8:02\u202fAM - ',
 '3/26/25, 8:02\u202fAM - ',
 '3/26/25, 8:02\u202fAM - ',
 '3/26/25, 8:02\u202fAM - ',
 '3/27/25, 8:36\u202fAM - ',
 '3/27/25, 8:36\u202fAM - ',
 '3/27/25, 8:36\u202fAM - ',
 '3/27/25, 8:36\u202fAM - ',
 '3/27/25, 8:36\u202fAM - ',
 '3/27/25, 8:36\u202fAM - ',
 '3/27/25, 8:36\u202fAM - ',
 '3/27/25, 8:36\u202fAM - ',
 '4/2/25, 9:51\u202fAM - ',
 '4/3/25, 8:41\u202fAM - ',
 '4/3/25, 8:41\u202fAM - ',
 '4/3/25, 8:41\u202fAM - ',
 '4/3/25, 8:41\u202fAM - ',
 '4/3/25, 8:41\u202fAM - ',
 '4/3/25, 8:41\u202fAM - ',
 '4/3/25, 8:41\u202fAM - ',
 '4/3/25, 8:41\u202fAM - ',
 '4/7/25, 10:06\u202fAM - ',
 '4/7/25, 10:06\u202fAM - ',
 '4/7/25, 10:07\u202fAM - ',
 '4/10/25, 8:45\u202fAM - ',
 '4/10/25, 8:45\u202fAM - ',
 '4/10/25, 8:45\u202fAM - ',
 '4/10/25, 8:45\u202fAM - ',
 '4/10/25, 8:45\u202fAM - ',
 '4/10/25, 8:45\u202fAM - ',
 '4/10/25, 8:45\u202fAM - ',
 '4/10/25, 8:45\u202fAM - ',
 '4/10/25, 10:22\u202fAM - ',
 '4/16/25, 8:36\u202fPM - ',
 '4/16/25, 8:36\u202fPM - ',
 '4/16/25, 8:36\u202fPM - ',
 '4/16/25, 8:37\u202fPM - ',
 '4/22/25, 8:36\u202fAM - ',
 '4/22/25, 8:36\u202fAM - ',
 '4/22/25, 8:36\u202fAM - ',
 '4/22/25, 10:45\u202fAM - ',
 '4/23/25, 8:03\u202fAM - ',
 '4/23/25, 10:08\u202fAM - ',
 '4/23/25, 10:08\u202fAM - ',
 '4/23/25, 10:08\u202fAM - ',
 '4/24/25, 10:55\u202fAM - ',
 '4/25/25, 12:29\u202fPM - ',
 '4/25/25, 12:40\u202fPM - ',
 '4/25/25, 6:03\u202fPM - ',
 '4/25/25, 7:33\u202fPM - ',
 '5/1/25, 10:08\u202fAM - ',
 '5/1/25, 10:08\u202fAM - ',
 '5/3/25, 6:04\u202fPM - ',
 '6/10/25, 8:17\u202fAM - ',
 '6/10/25, 8:17\u202fAM - ',
 '7/17/25, 8:48\u202fAM - ',
 '7/17/25, 8:48\u202fAM - ',
 '7/17/25, 8:48\u202fAM - ',
 '7/17/25, 8:48\u202fAM - ',
 '7/17/25, 8:48\u202fAM - ',
 '7/22/25, 8:17\u202fAM - ',
 '7/23/25, 10:31\u202fAM - ',
 '7/30/25, 5:31\u202fPM - ',
 '7/30/25, 5:44\u202fPM - ',
 '7/30/25, 5:44\u202fPM - ',
 '7/30/25, 5:44\u202fPM - ',
 '7/30/25, 5:44\u202fPM - ',
 '7/30/25, 5:44\u202fPM - ',
 '7/30/25, 5:44\u202fPM - ',
 '7/30/25, 5:44\u202fPM - ',
 '7/30/25, 5:45\u202fPM - ',
 '7/30/25, 5:45\u202fPM - ',
 '8/1/25, 9:44\u202fAM - ',
 '8/20/25, 12:56\u202fPM - ',
 '8/28/25, 6:26\u202fPM - ',
 '9/5/25, 6:53\u202fPM - ',
 '9/5/25, 6:53\u202fPM - ',
 '9/5/25, 6:53\u202fPM - ',
 '9/5/25, 6:58\u202fPM - ',
 '9/5/25, 7:08\u202fPM - ',
 '9/17/25, 9:11\u202fAM - ',
 '9/17/25, 9:11\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/6/25, 8:14\u202fAM - ',
 '10/16/25, 1:15\u202fPM - ',
 '10/21/25, 10:18\u202fAM - ',
 '10/22/25, 4:51\u202fAM - ',
 '10/22/25, 9:07\u202fAM - ',
 '10/22/25, 10:09\u202fAM - ',
 '10/22/25, 10:53\u202fAM - ',
 '10/22/25, 11:49\u202fAM - ',
 '10/22/25, 11:56\u202fAM - ',
 '10/22/25, 12:13\u202fPM - ',
 '10/22/25, 9:31\u202fPM - ',
 '10/30/25, 11:24\u202fAM - ',
 '10/30/25, 11:24\u202fAM - ',
 '10/30/25, 11:27\u202fAM - ',
 '10/30/25, 11:27\u202fAM - ',
 '10/30/25, 11:27\u202fAM - ',
 '10/30/25, 11:54\u202fAM - ',
 '12/2/25, 1:02\u202fPM - ',
 '12/2/25, 1:16\u202fPM - ',
 '12/11/25, 9:16\u202fAM - ',
 '1/7/26, 8:20\u202fAM - ',
 '1/7/26, 8:20\u202fAM - ',
 '1/7/26, 8:47\u202fAM - ',
 '1/7/26, 8:47\u202fAM - ',
 '1/7/26, 9:05\u202fAM - ',
 '1/7/26, 9:05\u202fAM - ',
 '1/7/26, 9:07\u202fAM - ',
 '1/7/26, 9:07\u202fAM - ',
 '1/7/26, 9:08\u202fAM - ',
 '1/7/26, 9:11\u202fAM - ',
 '1/8/26, 12:23\u202fPM - ',
 '1/8/26, 12:23\u202fPM - ',
 '1/8/26, 12:36\u202fPM - ',
 '1/15/26, 8:31\u202fAM - ',
 '1/15/26, 8:33\u202fAM - ',
 '1/15/26, 8:48\u202fAM - ',
 '1/21/26, 8:20\u202fAM - ',
 '1/21/26, 8:20\u202fAM - ',
 '1/21/26, 8:20\u202fAM - ',
 '1/21/26, 8:20\u202fAM - ',
 '1/22/26, 12:27\u202fPM - ',
 '1/22/26, 12:27\u202fPM - ',
 '1/22/26, 12:27\u202fPM - ',
 '1/22/26, 12:27\u202fPM - ',
 '1/22/26, 12:27\u202fPM - ',
 '1/22/26, 12:28\u202fPM - ',
 '1/22/26, 12:30\u202fPM - ']

In [43]:
df = pd.DataFrame({'user_message':messages, "message_date":dates})
# conver message_data types
df['message_date'] = df['message_date'].str.replace('\u202f', ' ', regex=False)

df['message_date'] = pd.to_datetime(
    df['message_date'],
    format='%d/%m/%y, %I:%M %p - '
)

df.rename(columns={'message_date': 'date'}, inplace=True)

df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. O... 2025-08-18 19:19:00
1  Vikram Baladaniya Vijapadi 2 created group "12... 2024-09-11 21:02:00
2                                   You were added\n 2024-09-11 21:02:00
3                 Nirav Godhaniya: <Media omitted>\n 2025-08-22 09:56:00
4  Nirav Godhaniya: Badani akho lidha pasi Maro b... 2025-08-22 09:56:00

In [44]:

users = []
messages = []
for message in df['user_message']:
    entry = re.split('([\w\W]+?):\s', message)
    if entry[1:]:  # user name
        users.append(entry[1])
        messages.append(" ".join(entry[2:]))
    else:
        users.append('group_notification')
        messages.append(entry[0])

df['user'] = users
df['message'] = messages
df.drop(columns=['user_message'], inplace=True)

df.head(10)

,date,user,message
0,2025-08-18 19:19:00,group_notification,Messages and calls are end-to-end encrypted. O...
1,2024-09-11 21:02:00,group_notification,"Vikram Baladaniya Vijapadi 2 created group ""12..."
2,2024-09-11 21:02:00,group_notification,You were added\n
3,2025-08-22 09:56:00,Nirav Godhaniya,<Media omitted>\n
4,2025-08-22 09:56:00,Nirav Godhaniya,Badani akho lidha pasi Maro bhaibandh!\n
5,2025-08-22 09:57:00,Manish Joiya Mahuva,Zala ko kisine aada ghala\n
6,2025-08-22 10:05:00,Nirav Godhaniya,<Media omitted>\n
7,2025-08-22 10:05:00,Nirav Godhaniya,Have to hamna mitha modha karva nu thay jase !\n
8,2025-08-22 10:06:00,Vikram Baladaniya Vijapadi 2,Kem\n
9,2025-08-22 10:07:00,Vikram Baladaniya Vijapadi 2,Tushar e-riksha vala🤘🤘\n

In [49]:
df['year']=df['date'].dt.year

In [50]:
df.head()

,date,user,message,year
0,2025-08-18 19:19:00,group_notification,Messages and calls are end-to-end encrypted. O...,2025
1,2024-09-11 21:02:00,group_notification,"Vikram Baladaniya Vijapadi 2 created group ""12...",2024
2,2024-09-11 21:02:00,group_notification,You were added\n,2024
3,2025-08-22 09:56:00,Nirav Godhaniya,<Media omitted>\n,2025
4,2025-08-22 09:56:00,Nirav Godhaniya,Badani akho lidha pasi Maro bhaibandh!\n,2025

In [53]:
df['month']=df['date'].dt.month_name()

In [56]:
df['day']=df['date'].dt.day

In [57]:
df['hour'] = df['date'].dt.hour

In [58]:
df['minute']= df['date'].dt.minute

In [59]:
df.head()

,date,user,message,year,month,day,hour,minute
0,2025-08-18 19:19:00,group_notification,Messages and calls are end-to-end encrypted. O...,2025,August,18,19,19
1,2024-09-11 21:02:00,group_notification,"Vikram Baladaniya Vijapadi 2 created group ""12...",2024,September,11,21,2
2,2024-09-11 21:02:00,group_notification,You were added\n,2024,September,11,21,2
3,2025-08-22 09:56:00,Nirav Godhaniya,<Media omitted>\n,2025,August,22,9,56
4,2025-08-22 09:56:00,Nirav Godhaniya,Badani akho lidha pasi Maro bhaibandh!\n,2025,August,22,9,56